# Generated by Django 4.0.4 on 2023-10-29 17:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0002_alter_activitysubscription_weekday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activitysubscription',
            unique_together={('hour', 'weekday', 'type'), ('user', 'weekday', 'hour')},
        ),
    ]
