# Generated by Django 4.0.4 on 2023-10-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_activitysubscription_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubscriptionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'activity subscription proxy',
                'verbose_name_plural': 'activity subscription proxys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reservations.activitysubscription',),
        ),
    ]
