# Generated by Django 4.0.4 on 2023-10-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_activitysubscriptionproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubscription',
            name='frozen',
        ),
        migrations.AddField(
            model_name='activitysubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
